### ISSUE TITLE
Ban until specific date

### ISSUE THREAD

**Issue by evgfilim1** [evgfilim1/userbot#18]
Same behavior as in `.remind` and `.remindme`

https://github.com/evgfilim1/userbot/blob/24c0910a48490b0ca1176c0d2805d23108b3f9d2/userbot/commands/reminders.py#L45
https://github.com/evgfilim1/userbot/blob/24c0910a48490b0ca1176c0d2805d23108b3f9d2/userbot/commands/reminders.py#L22-L38

**Comment by 7DSMeliodas** [comment]
@evgfilim1 What’s the problem ? Or just to do ?

**Comment by evgfilim1** [comment]
@7DSMeliodas Just another to-do item, yeah
