### ISSUE TITLE
Bot stats

### ISSUE THREAD

**Issue by evgfilim1** [evgfilim1/userbot#24]
> .stats — show some stats for the bot and the user

Example output:
> ⚙ Uptime: 1h2m3s
> ⭐️ Doesn't have premium
> 💬 Total chats: 1000
> 💬 Unread: 2
> 📥 Archived chats: 50
> 👤 Private chats: 400
> 👥 Groups: 400
> 📢 Channels: 200
> 🎞 Saved GIFs: 300
> 📑 Saved stickers: 200
> 🕒 Archived stickers: 300
> ...

Take appropriate icons from https://t.me/addemoji/IconsInTg for premium users
![image](https://user-images.githubusercontent.com/17182159/193342948-74948749-159a-4381-8133-dc4b484b954a.png)

**Comment by 7DSMeliodas** [comment]
@evgfilim1 Nice
