### ISSUE TITLE
Wakatime stats

### ISSUE THREAD

**Issue by evgfilim1** [evgfilim1/userbot#25]
> .wakastats — Fetch wakatime.com stats for myself

API: https://wakatime.com/developers

**Comment by krau5** [comment]
@evgfilim1 assign it to me and provide some requirements regarding its implementation

**Comment by coalus** [comment]
@krau5 any activity on this issue?

**Comment by krau5** [comment]
> @krau5 any activity on this issue?

I'll make a PR ASAP, so you'll see the progress 👀
